server:
  port: ${PORT:8080}

spring:
  datasource:
    # Syntax: ${VAR_NAME:Default_Value_For_Local}
    # Render will inject DB_URL. Local will use the jdbc string after the colon.
    url: ${DB_URL:jdbc:postgresql://ep-autumn-surf-agp3377v-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_ay0qkWNSwim8}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      # Render injects REDIS_HOST. Local uses the Upstash URL.
      host: ${REDIS_HOST:deep-slug-47623.upstash.io}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:AboHAAIncDEyYTc4YzkzYjY3ZWU0YzZkYjg3ZTA3ZTlmZTQwNWI4MnAxNDc2MjM}
      ssl:
        enabled: ${REDIS_SSL:true}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: FullStack Shop API
    version: 1.0.0

jwt:
  secret: ${JWT_SECRET:secret256BitKeyPentruDev123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:3600}

roles:
  admin: ADMIN
  customer: CUSTOMER

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG